# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mytools_gui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(485, 277)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 461, 208))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.scrollAreaWidgetContents)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.var_numer_of_line = QtWidgets.QSpinBox(self.tab)
        self.var_numer_of_line.setProperty("value", 1)
        self.var_numer_of_line.setObjectName("var_numer_of_line")
        self.horizontalLayout.addWidget(self.var_numer_of_line)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.copytext = QtWidgets.QPlainTextEdit(self.tab)
        self.copytext.setPlainText("")
        self.copytext.setObjectName("copytext")
        self.verticalLayout_2.addWidget(self.copytext)
        self.pushButton_4 = QtWidgets.QPushButton(self.tab)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_2.addWidget(self.pushButton_4)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 1, 3, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_3.addWidget(self.pushButton_2, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.plusBox = QtWidgets.QComboBox(self.tab)
        self.plusBox.setMinimumSize(QtCore.QSize(50, 24))
        self.plusBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.plusBox.setObjectName("plusBox")
        self.plusBox.addItem("")
        self.plusBox.addItem("")
        self.verticalLayout.addWidget(self.plusBox)
        self.directBox = QtWidgets.QComboBox(self.tab)
        self.directBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.directBox.setObjectName("directBox")
        self.directBox.addItem("")
        self.directBox.addItem("")
        self.directBox.addItem("")
        self.verticalLayout.addWidget(self.directBox)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.symbolBox = QtWidgets.QComboBox(self.tab)
        self.symbolBox.setEditable(True)
        self.symbolBox.setObjectName("symbolBox")
        self.symbolBox.addItem("")
        self.symbolBox.addItem("")
        self.symbolBox.addItem("")
        self.horizontalLayout_2.addWidget(self.symbolBox)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 485, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.pushButton_2.clicked.connect(MainWindow.to_self_equal)
        self.pushButton.clicked.connect(MainWindow.to_list)
        self.pushButton_4.clicked.connect(MainWindow.add_copy)
        self.pushButton_3.clicked.connect(MainWindow.text_symbol)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "to_list"))
        self.pushButton_4.setText(_translate("MainWindow", "copy"))
        self.pushButton_2.setText(_translate("MainWindow", "to_self_equal"))
        self.pushButton_3.setText(_translate("MainWindow", "text_symbol"))
        self.plusBox.setItemText(0, _translate("MainWindow", "+"))
        self.plusBox.setItemText(1, _translate("MainWindow", "-"))
        self.directBox.setItemText(0, _translate("MainWindow", "left"))
        self.directBox.setItemText(1, _translate("MainWindow", "right"))
        self.directBox.setItemText(2, _translate("MainWindow", "all"))
        self.symbolBox.setItemText(0, _translate("MainWindow", "*"))
        self.symbolBox.setItemText(1, _translate("MainWindow", "·"))
        self.symbolBox.setItemText(2, _translate("MainWindow", "smile"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tools"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))

