# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wechat_window.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(446, 645)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 422, 570))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.Button_login = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.Button_login.setObjectName("Button_login")
        self.gridLayout.addWidget(self.Button_login, 0, 0, 1, 1)
        self.Button_logout = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.Button_logout.setObjectName("Button_logout")
        self.gridLayout.addWidget(self.Button_logout, 0, 1, 1, 1)
        self.friend_tableView = QtWidgets.QTableView(self.scrollAreaWidgetContents)
        self.friend_tableView.setMinimumSize(QtCore.QSize(400, 0))
        self.friend_tableView.setObjectName("friend_tableView")
        self.friend_tableView.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.friend_tableView, 1, 0, 1, 2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_4.addWidget(self.scrollArea, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 446, 26))
        self.menubar.setObjectName("menubar")
        self.menuTotal_Status = QtWidgets.QMenu(self.menubar)
        self.menuTotal_Status.setObjectName("menuTotal_Status")
        self.menuStatistic_data = QtWidgets.QMenu(self.menuTotal_Status)
        self.menuStatistic_data.setObjectName("menuStatistic_data")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSex = QtWidgets.QAction(MainWindow)
        self.actionSex.setObjectName("actionSex")
        self.actionProvince = QtWidgets.QAction(MainWindow)
        self.actionProvince.setObjectName("actionProvince")
        self.actionCity = QtWidgets.QAction(MainWindow)
        self.actionCity.setObjectName("actionCity")
        self.actionLogin = QtWidgets.QAction(MainWindow)
        self.actionLogin.setObjectName("actionLogin")
        self.actionLogout = QtWidgets.QAction(MainWindow)
        self.actionLogout.setObjectName("actionLogout")
        self.menuStatistic_data.addAction(self.actionSex)
        self.menuStatistic_data.addAction(self.actionProvince)
        self.menuStatistic_data.addAction(self.actionCity)
        self.menuTotal_Status.addAction(self.menuStatistic_data.menuAction())
        self.menuTotal_Status.addAction(self.actionLogin)
        self.menuTotal_Status.addAction(self.actionLogout)
        self.menubar.addAction(self.menuTotal_Status.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.Button_login.clicked.connect(MainWindow.login)
        self.Button_logout.clicked.connect(MainWindow.logout)
        self.friend_tableView.doubleClicked['QModelIndex'].connect(MainWindow.msg_en)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Button_login.setText(_translate("MainWindow", "Login"))
        self.Button_logout.setText(_translate("MainWindow", "Log out"))
        self.menuTotal_Status.setTitle(_translate("MainWindow", "Status"))
        self.menuStatistic_data.setTitle(_translate("MainWindow", "Statistic data"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionSex.setText(_translate("MainWindow", "Sex"))
        self.actionProvince.setText(_translate("MainWindow", "Province"))
        self.actionCity.setText(_translate("MainWindow", "City"))
        self.actionLogin.setText(_translate("MainWindow", "Login"))
        self.actionLogout.setText(_translate("MainWindow", "Logout"))

